


name: Deploy-iotex-docs-to-GitHub-Page
on:
  push:
    branches:
      - master

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build-docs
        run: |
          npm install
          NODE_ENV=production npm run build
      - name: Commit-files
        run: |
          cd docs/.vuepress/dist
          echo 'docs-old.iotex.io' > CNAME
          git init
          git config --global user.email "puncsky@users.noreply.github.com"
          git config --global user.name "puncsky"
          git add -A
          git commit -m 'deploy'
      - name: Deploy-Docs-to-github-page
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          force: true
          directory: 'docs/.vuepress/dist'
